spring.application.name=foodiesapi

spring.mongodb.uri=mongodb://localhost:27017/foodies

aws.region=us-east-1
aws.s3.bucket=foodies-app123
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.servlet.context-path=/api